- op: add
  path: /jobs/cargo-test/steps/1/with/target
  value: wasm32-unknown-unknown
- op: add
  path: /jobs/cargo-test/steps/2
  value:
      uses: IronCoreLabs/rust-install@v0.1.0
      with:
          crate: wasm-bindgen-cli
          accesskey: AKIAU2WBY6VDTC563V7G
          secretkey: ${{ secrets.TOOL_CACHE_SECRET_KEY }}
          os: ubuntu-20.04
- op: add
  path: /jobs/coverage/steps/1/with/target
  value: wasm32-unknown-unknown
- op: add
  path: /jobs/coverage/steps/2
  value:
      uses: IronCoreLabs/rust-install@v0.1.0
      with:
          crate: wasm-bindgen-cli
          accesskey: AKIAU2WBY6VDTC563V7G
          secretkey: ${{ secrets.TOOL_CACHE_SECRET_KEY }}
          os: ubuntu-20.04
