- op: add
  path: /jobs/test/steps/1
  value:
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
- op: add
  path: /jobs/test/steps/2
  value:
      uses: IronCoreLabs/rust-install@v0.1.0
      with:
          crate: wasm-bindgen-cli
          accesskey: ${{ secrets.TOOL_CACHE_KEY_ID }}
          secretkey: ${{ secrets.TOOL_CACHE_SECRET_KEY }}
          os: ubuntu-20.04
- op: add
  path: /jobs/test/steps/6
  value:
      name: Compile
      run: yarn run compile
# Coverage doesn't work for this repo
- op: remove
  path: /jobs/test/steps/8
