- op: add
  path: /jobs/test/steps/1
  value:
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
- op: add
  path: /jobs/test/steps/2
  value:
      uses: actions-rs/install@v0.1
      with:
          crate: wasm-bindgen-cli
- op: add
  path: /jobs/test/steps/3
  value:
      run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
